apiVersion: 1.0.0
kind: Transform
name: fhir-pipeline-monitoring
profile: FHIR_PIPELINE_MONITORING
file: pipelines/monitoring.py
entrypoint: generate_monitoring_metrics
inputs:
  - path: /control/fhir_cursors
  - path: /metrics/transform_metrics
    optional: true
  - path: /secrets/epic_token
  - path: /control/workflow_status
    optional: true
  - path: /config/resources_config.yaml
  - path: /silver/fhir_normalized
    optional: true
outputs:
  - path: /monitoring/pipeline_metrics
resources:
  memory: 2Gi
  timeout: 600s  # 10 minutes
schedule:
  cron: "0 6 * * *"   # Run daily at 6 AM, after all other transforms
dependencies:
  - transform: gold-patient-summary
  - transform: gold-encounter-summary
  - transform: gold-medication-summary
description: |
  Generates comprehensive monitoring metrics for the FHIR pipeline. This transform
  aggregates information from various pipeline components including token status,
  extraction statistics, transformation metrics, and data quality indicators. 
  The resulting dataset provides a holistic view of pipeline health and can be
  used for alerting, reporting, and troubleshooting. 