apiVersion: 1.0.0
kind: Transform
name: gold-patient-timeline
file: pipelines/gold/patient_timeline.py
entrypoint: create_patient_timeline
inputs:
  - path: /silver/fhir_normalized/observation
  - path: /silver/fhir_normalized/condition
  - path: /silver/fhir_normalized/encounter
  - path: /silver/fhir_normalized/medicationrequest
  - path: /silver/fhir_normalized/diagnosticreport
outputs:
  - path: /gold/patient_timeline
resources:
  memory: 12Gi
schedule:
  after: gold-patient-summary
permissions:
  - principal: ROLE_HEALTH_ANALYST
    actions: [READ] 