version: '3.8'

services:
  pathling:
    image: aehrc/pathling:5.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./pathling-data:/usr/share/pathling/data
    environment:
      - PATHLING_TERMINOLOGY_SERVER_URL=https://r4.ontoserver.csiro.au/fhir
      - PATHLING_CORS_ENABLED=true
      - PATHLING_VALIDATION_ENABLED=false
      - PATHLING_EXPLAIN_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 10s
      timeout: 5s
      retries: 5 