name: Docker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and test
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: myapp:test
        cache-from: type=gha
        cache-to: type=gha,mode=max 